### ISSUE TITLE
Broken window/popup transparency on Windows

### ISSUE THREAD

**Issue by Guerra24** [danirod/cartero#19]
![image](https://github.com/danirod/cartero/assets/9023392/3b18fce4-3232-4ea2-a45a-e63fa9e63ffc)

Rendering info as requested
![image](https://github.com/danirod/cartero/assets/9023392/28b0dabf-c2a4-4915-9c7c-f3cbb14b7ec6)
![image](https://github.com/danirod/cartero/assets/9023392/f3f275ca-a726-43a8-8cbd-3dc793287651)
![image](https://github.com/danirod/cartero/assets/9023392/0ee5165c-f518-453a-be5c-7fc3ea24004c)
![image](https://github.com/danirod/cartero/assets/9023392/99758acb-0835-42dd-83ca-a0e884a3548b)

**Comment by danirod** [comment]
Odd, I have the same settings and the same graphics card and mine doesn't do that. However, my GL_VERSION is reported as 4.6.0 NVIDIA 545.92. Maybe it is a thing with the NVIDIA driver version.

![imagen](https://github.com/danirod/cartero/assets/1568690/c03bd792-d016-432e-8ded-a7252ade4425)

![imagen](https://github.com/danirod/cartero/assets/1568690/3cfc4cac-e527-4c06-b2a6-59060f800419)

**Comment by danirod** [comment]
As of 695f537f9b3bef835dd05d2172cb0d793a4a4b6f, I am forcing Cartero to run using the Cairo renderer when running in Windows.

I'd ask you to try a more recent [nightly](https://nightly.link/danirod/cartero/workflows/nightly.yaml/trunk/es.danirod.Cartero-windows-x86_64.zip) version to see if this is still an issue on \*your\* NVIDIA driver version.

**Comment by Guerra24** [comment]
Tested the old version after updating the drivers, and now only the main window remains with black borders.
![image](https://github.com/user-attachments/assets/b3c415b5-1aa9-42c5-994d-ef5e536571e8)
Popups, context menus and child windows render correctly.
![image](https://github.com/user-attachments/assets/e9b2b512-2128-4dfb-97cf-f308bd0d7fcd)

The software rendered version works correctly on both old and new drivers. So no more issues on my end.
![image](https://github.com/user-attachments/assets/1ff42c33-79f9-4c75-9ae7-de4a53618da6)

**Comment by danirod** [comment]
I am closing this for now then, even though there will be more QOL changes for Windows in the future.
