### ISSUE TITLE
Default language not recognized on Windows 11 PRO (23H2)

### ISSUE THREAD

**Issue by richardogcc** [danirod/cartero#42]
I'm experiencing an issue with the Cartero application on Windows 11 PRO (23H2) where the default language is not being recognized. Specifically, the application is not detecting Spanish as the default language, which is set as the system language on my machine.

### Steps to reproduce:
- Install Cartero on Windows 11 PRO (23H2) with Spanish set as the system language.
- Launch Cartero.
- Observe that the application does not recognize Spanish as the default language.

### Expected behavior:
The application should recognize Spanish as the default language and adjust its language settings accordingly.

### System information:
Operating System: Windows 11 PRO (23H2)
Language: Spanish (set as system language)

Let me know if you'd like me to add or modify anything!

**Comment by richardogcc** [comment]
This issue only occurs the first time you download and start Cartero, as far as I've been able to verify. When you restart the computer, the language is applied correctly and changing the default language, logging out, and logging back in changes the language accordingly in a correct manner.

**Comment by danirod** [comment]
I can't verify this on my Windows system. Windows 11 Pro, 23H2, 22631.3880.

My computer's locale is set to Spanish. If I download again Cartero and start bin/cartero.exe, I see the UI in Spanish.

**Comment by richardogcc** [comment]
I'll try to reproduce the issue again on a virtual machine as soon as I have some time and will come back with more info. Is it possible that the first time the program is launched, a variable is missing and it takes the default language regardless of the system language?

**Comment by danirod** [comment]
> I'll try to reproduce the issue again on a virtual machine as soon as I have some time and will come back with more info

Yeah, now worries. I am currently installing a MUI pack in one of the [official Windows VMs](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) and I'll try to check if something different happens.

. . .

> Is it possible that the first time the program is launched, a variable is missing and it takes the default language regardless of the system language?

While in theory it is possible to override the language using the `LANGUAGE` environment variable, it should pick the system language by default. The only thing I can imagine making it break is if the system language has just been changed and the computer did not reboot yet. Maybe Windows does not report the language properly, or maybe gettext doesn't pick the change until the next reboot.

**Comment by danirod** [comment]
It still greets me in Spanish right after executing the application for the first time.

![imagen](https://github.com/user-attachments/assets/d1797adf-7e59-4379-8180-3a2e18a39ba9)

**Comment by richardogcc** [comment]
After conducting some additional tests, I have realized that the system's default language is indeed taken into account. It's possible that the bug I experienced was an isolated incident or due to some inconsistency in my system, so I apologize for any inconvenience and this issue can be closed.
