### ISSUE TITLE
 Productivity / Accessibility in cartero

### ISSUE THREAD

**Issue by javivi02** [danirod/cartero#48]
When enter the API in the text bar i want to access, it would be nice if after **press enter**, send the request.

I have tried that it does not work so much in Ubuntu with Windows.

The app looks amazing.

Thanks.

**Comment by danirod** [comment]
Currently this can be achieved using Ctrl + Enter on GNU/Linux and Windows (Cmd + Enter on macOS).

**Comment by javivi02** [comment]
Great Dani it works, I use it like this
