### ISSUE TITLE
"About Window" Does not change language

### ISSUE THREAD

**Issue by altaskur** [danirod/cartero#56]
# Issue: "About" Window Does Not Change Language

## Description

I noticed that the "About window" of the application does not change its language. While the rest of the application is correctly displayed in this case, Spanish , the "About window" remains in English.

![image](https://github.com/user-attachments/assets/96daecaf-7fb4-42e4-bb93-7a348bc905bc)

## Expected Behavior
The "About window" should display text in the os language, in this case, Spanish, along with the rest of the application.

## Actual Behavior:
The "About window" remains in English regardless of the language setting.

## Environment

- Application Version: 0.1.1
- OS:  Windows 11

**Comment by danirod** [comment]
Fixed in https://github.com/danirod/cartero/pull/70, it will be visible in future app updates.

![image](https://github.com/user-attachments/assets/8be5ce3d-52a3-4f9b-a1bb-65e325bfa1a0)
