### ISSUE TITLE
El contenido del resultado de la consulta no se adapta al tamaño

### ISSUE THREAD

**Issue by Robin-3** [danirod/cartero#67]
El contenido del resultado de la consulta no se siempre se adapta al tamaño del contenedor, lo que causa que el resultado desborde y aparezca un deslizador horizontal. Este comportamiento ocurre incluso cuando en las configuraciones se indica que en la apariencia del cuerpo `Se adapte el contenido`.

**Pasos para reproducir el problema:**
1. Realizar una petición HTTP a `https://randomuser.me/api/?results=2&format=csv`.

![image](https://github.com/user-attachments/assets/b7d7c053-f64c-462c-a985-cf976f7b7817)
![image](https://github.com/user-attachments/assets/cf931749-cf07-4f16-97b5-c10d5251a355)

**Entorno:**
- Cartero: 0.1.1
- Windows 10 Home Single Language 22H2, procesador basado en x64

**Comment by danirod** [comment]
Confirmo que me está ocurriendo, ignora la opción de adaptar al contenido si una línea no tiene ningún espacio. Meto al kanban.

**Comment by danirod** [comment]
Ha quedado corregido en el PR https://github.com/danirod/cartero/pull/69 y el fix saldrá en la próxima actualización.

![image](https://github.com/user-attachments/assets/ba782198-3d9e-4f44-bd70-87328124ed64)
