### ISSUE TITLE
Al guardar una petición se guarda junto a la versión previa

### ISSUE THREAD

**Issue by Robin-3** [danirod/cartero#73]
Al guardar una petición:
- Si es la primera vez se guarda los datos.
- Al realizarlo una segunda vez o más se genera un archivo adicional que conserva los datos previos.

**Pasos para reproducir el problema:**
1. Guardar el archivo más de una sola vez.

[cartero-bug.webm](https://github.com/user-attachments/assets/554b1171-4e25-4793-8437-7a95c7062d69)

**Entorno:**

- Cartero: 0.1.1
- Windows 10 Home Single Language 22H2, procesador basado en x64

**Comment by danirod** [comment]
Sí, me he dado cuenta de esto. Se crea un backup de la vieja versión cuando pulsas Guardar. No sabía que Gio.File permitía hacer esto gratis y sin programar nada más, y también me sorprendió la primera vez que vi un .cartero~ en mi directorio de trabajo.

En https://github.com/danirod/cartero/issues/59 tengo como tarea que quiero meter en la pantalla de opciones una forma de activar o desactivar esto. Por un lado yo no lo veo necesario en la mayoría de casos (sobre todo si ya tienes Git), pero me parece una opción interesante de activar para gente que quiera tener una forma de volver atrás si se da cuenta que se ha equivocado terriblemente al pulsar Guardar.
