### ISSUE TITLE
AUR PKGBUILD

### ISSUE THREAD

**Issue by egerardoqd** [danirod/cartero#90]
instalar Cartero en Arch da error al no encontrar el compilador rustc.
Lo pude solucionar con el siguiente comando `rustup default stable`
se podría solucionar agregando esto al PKGBUILD?

```
prepare() {
    rustup default stable
}
```

**Comment by danirod** [comment]
No sé si eso será posible de incorporar al PKGBUILD de AUR porque la dependencia de Rust está declarada tanto para `cartero` como para `cartero-git`, y pide [rust](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cartero-git&id=4df1cf4c3b161ac613e4f8979b86dcbfbe457841#n10). En una máquina virtual vacía y sin nada pre-instalado, sí compruebo que instala rust, que proporciona rustc.

Ahora bien, el paquete `rust` tiene varios providers, y si instalas otro paquete que lo proporcione (como `rust-git` o `rustup`), lo va a tratar como aceptable y lo va a usar en vez de instalarte el paquete rust.

¿Instalaste rustup a través de pacman también? En ese caso es probable que debas hacer igualmente antes que nada un rustup default stable, para asegurar que tienes una toolchain, pero eso es externo al proceso de compilación.

En principio no me veo favorable de agregar un comando rustup a los PKGBUILD porque alguien que instale directamente `rust` o `rust-nightly` pero no `rustup` va a recibir un error ahí.

Si todo está correcto por tu lado, me apunto para investigar este hecho igualmente.

**Comment by egerardoqd** [comment]
En mi sistema ya tenía instalado rustup (a través de AUR) aunque este último no estaba configurado, creo que de allí viene el error. Entiendo que es un problema muy particular, igual gracias por la explicación.

**Comment by danirod** [comment]
No problem! Estoy para ayudar, como siempre.

Sí, considero que es específico porque los PKGBUILDs solo piden un rustc, si se obtiene desde fuera mediante rustup, es algo que se tiene que configurar por fuera.

Voy a cerrar el issue para indicar que ha quedado resuelto, pero cualquier cosa, los comentarios siguen abiertos :)
